name: Rust CI

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: markets-runner
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ""
          key: ""

      - run: cargo build --release --all-features
