name: Rust CI

on:
  push:
    branches: ["dev", "main"]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"

  pull_request:
    branches: ["dev", "main"]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ""
          key: ""

      - name: Check
        run: cargo check --all-features --all-targets

      - name: Rustfmt
        run: cargo fmt --check --all

      - name: Cargo sort
        run: cargo install cargo-sort && cargo sort --grouped --check

      - name: Clippy
        run: cargo clippy --release --all-targets --all-features

      - name: Build
        run: cargo build --release --all-features --all-targets
